version: "3.3"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: technoweb
      MONGO_INITDB_ROOT_PASSWORD: technoweb
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb: