version: "3.3"
services:
  mongodb:
    image: mongo:5.0-focal
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: technoweb
      MONGO_INITDB_ROOT_PASSWORD: technoweb
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb: